### ISSUE TITLE
update-templates may not be copying the buildwin directory

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/shipdriver_pi#343] opened 2021-12-10 17:40 UTC
Just used update-templates with JavaScript_pi. The source was outdated. _buildwin_ was there but removed along with _build-osx_.

**Comment by Rasbats** [comment] 2021-12-10 17:42
.gitignore has build & build-* but not buildwin.

**Comment by Rasbats** [comment] 2021-12-10 18:20
Just did a manual copy of the directories ci, cmake and .circleci from ShipDriver master and Javascript_pi is now building. Still the flatpak problem with PR: [https://github.com/Rasbats/shipdriver_pi/pull/342](https://github.com/Rasbats/shipdriver_pi/pull/342)

**Comment by leamas** [comment] 2021-12-10 21:44
Something is rotten in CircleCI. The exact same commit cd06376 builds fine for me, logs [here](https://app.circleci.com/pipelines/github/leamas). That should verify that the shipdriver base is sound. That is not to say that updates-templates is.

The removed buildwin directory is caused by rightfullty remove the NSIS files but not taking care of win_deps.bat. Should be a simple fix, PR shortly.

> The source was outdated.

Could you be as bit more specific here? What was outdated,  and how?

**Comment by Rasbats** [comment] 2021-12-11 08:29
> The source was outdated

Tony had problems with the v0.5 branch of JavaScript. Eventually he worked around this by merging with the master branch and we compiled from that. But master was last worked on some months ago and needed updating. Hence the use of _update-templates_ and finding the bug with the script.

**Comment by leamas** [comment] 2021-12-13 19:27
As I understand it this issue is fixed in 57d5b88 and can be closed.  Or?

**Comment by leamas** [comment] 2021-12-17 16:01
@rasbats: Ping? ^

**Closed** 2021-12-17 16:25 UTC
