### ISSUE TITLE
Logbook- push to CS logbook-prod and plugins

### ISSUE THREAD

**Issue by rgleason** [Rasbats/shipdriver_pi#387] opened 2022-01-08 16:02 UTC
I was trying to push logbook builds to opencpn/plugins  here
Github  https://github.com/rgleason/LogbookKonni_pi/commits/master
These all landed in [Cloudsmith logbookkonni-alpha](https://cloudsmith.io/~opencpn/repos/logbookkonni-alpha/packages/)
Using "git push origin 1.4.25 + SD 3.0.1"  
Circleci shows that all [Logbook failed ](https://app.circleci.com/pipelines/github/rgleason/LogbookKonni_pi/138/workflows/572f5816-2925-497b-8511-23222369fb60) although it did get deployed to Cloudsmith.
Have just added a tag  "git tag v1.4.25"   (It seems to be pretty "empty"  in Circleci
and used "git push origin v1.4.25" to push the tag to github.
Now I am not finding Logbook v1.4.25 pushed into[ Cloudsmith logbookkonni-prod](https://cloudsmith.io/~opencpn/repos/logbookkonni-prod/packages/)
and it does not appear to have copied or pushed metadata to plugins/auto.  

What am I doing wrong?
I am using the master branch and tagging the commit, why doesn't the deployment land in CS logbook-prod?
I need to get it to land in logbook-prod at the very least, so I can push to opencpn/plugins by any means.
We are missing logbook in the catalog.

**Comment by rgleason** [comment] 2022-01-08 17:40
I still need to know the proper way to do this, however I am going to use the logbookkonni-alpha branch to populate the catalog because we are missing any logbook entries in the master catalog.
The alpha branch has a shorter 30 day retainage, so I need to get this resolved at some point.

**Comment by rgleason** [comment] 2022-01-08 17:50
This was quite simple to do from the updated master branch.

fcgle@Hesper MINGW64 ~/source/plugins (master)
$ ./download_xml_bash.sh logbookkonni 1.4 opencpn alpha

I would still like to know how exactly to do automatic.

**Comment by rgleason** [comment] 2022-01-08 17:52
These 8 are the only ones that built

        metadata/Logbook-1.4-darwin-wx315-10.13.6.xml
        metadata/Logbook-1.4-debian-10.xml
        metadata/Logbook-1.4-msvc-10.0.14393.xml
        metadata/Logbook-1.4-raspbian-10.xml
        metadata/Logbook-1.4-raspbian-9.13.xml
        metadata/Logbook-1.4-ubuntu-16.04.xml
        metadata/Logbook-1.4-ubuntu-18.04.xml
        metadata/Logbook-1.4-ubuntu-gtk3-18.04.xml
        metadata/Logbook-1.4-ubuntu-gtk3-20.04.xml

**Comment by Rasbats** [comment] 2022-01-08 18:31
New tag sd3.0.2-beta1 for use with _update-templates_. Might be worth testing with LogbookKonni. It solves the problem of missing Flatpak and Raspbian permission denied problem.

I am having problems with the Windows builds with this. [https://github.com/Rasbats/shipdriver_pi/issues/383](https://github.com/Rasbats/shipdriver_pi/issues/383)

>I would still like to know how exactly to do automatic.

You need to have stuff building and saving in Cloudsmith beta packages first. After that we can step through things.

**Comment by rgleason** [comment] 2022-01-08 19:23
1. I've brought my local and remote shipdriver_pi up to date with 
* v3.0                                    64c069a sd3.0.2-beta1

How do I do the update-templates?  Haven't found it in the instructions yet.

**Comment by rgleason** [comment] 2022-01-08 19:26
I found it in the main directory  along with Update-templates.md.

**Comment by rgleason** [comment] 2022-01-08 19:49
```
fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (master)
$ ./update-templates -T shipdriver/v3.0
+ source_treeish=shipdriver/v3.0
++ git status --porcelain
+ clean=
+ '[' -n '' ']'
+ '[' -z true ']'
+ git rev-parse --verify -q shipdriver/v3.0
+ echo 'Unknown tag or branch shipdriver/v3.0 -- giving up.'
Unknown tag or branch shipdriver/v3.0 -- giving up.
+ exit 1

fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (m
```

**Comment by leamas** [comment] 2022-01-08 20:27
> I don't think the path is correct. Does it need to be [...]

No. First of all you dont want the -T flag, it's basically development tools. The proposed way is the way described in _ update-templates -h_

**Comment by rgleason** [comment] 2022-01-08 23:46
Alec, the error says 

```
+ echo 'Unknown tag or branch shipdriver/v3.0 -- giving up.'
Unknown tag or branch shipdriver/v3.0 -- giving up.
```
I have looked at help and I used a shipdriver tag  "v3.0" an "update from the release branch", and it is not being found.therefore I think the path isn't right.
.
I am going to wait for further instructions instead of banging my head against the wall some more.

**Comment by rgleason** [comment] 2022-01-09 00:16
`./update-templates -l
`
Adds a new remote!!   This is necessary to avoid the previous errors.
The manual should mention this as a first necessary step.

```
fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (master)
$ update-templates -l
bash: update-templates: command not found

fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (master)
$ ./update-templates -l
Adding new shipdriver remote
sd3.0.0
sd3.0.0-beta1
sd3.0.0-beta2
sd3.0.0-rc1
sd3.0.1
sd3.0.1-beta1
sd3.0.1-beta4
sd3.0.1-beta5
sd3.0.2-beta1

fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (master)
$ git remote -v
origin  git@github.com:rgleason/LogbookKonni_pi.git (fetch)
origin  git@github.com:rgleason/LogbookKonni_pi.git (push)
shipdriver      https://github.com/Rasbats/shipdriver_pi.git (fetch)
shipdriver      https://github.com/Rasbats/shipdriver_pi.git (push)
upstream        https://github.com/delatbabel/LogbookKonni-1.2.git (fetch)
upstream        https://github.com/delatbabel/LogbookKonni-1.2.git (push)


```

**Comment by rgleason** [comment] 2022-01-09 00:47
in  update-templates.md

Add this please

Options:

**-l** lists available tags which can be used as _treeish_    (Necessary to do this first, adds a new remote "shipdriver" )

**Comment by rgleason** [comment] 2022-01-09 00:55
```
fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (master)
$ git checkout -b v3.0
Switched to a new branch 'v3.0'

fcgle@Hesper MINGW64 ~/source/logbookkonni_pi (v3.0)
$ ./update-templates sd3.0.2-beta1
Removing existing shipdriver remote.
Adding new shipdriver remote
Checking for updates of updates-templates script
e49825d7fb8bc6edd6448264622a4a217325c187
Updating cmake
rm 'cmake/AndroidLibs.cmake'
rm 'cmake/CmakeSetup.cmake'
rm 'cmake/GetArch.cmake'
rm 'cmake/Metadata.cmake'
rm 'cmake/PluginCompiler.cmake'
rm 'cmake/PluginInstall.cmake'
rm 'cmake/PluginLibs.cmake'
rm 'cmake/PluginLocalization.cmake'
rm 'cmake/PluginOptions.cmake'
rm 'cmake/PluginPackage.cmake'
rm 'cmake/PluginSetup.cmake'
rm 'cmake/Targets.cmake'
rm 'cmake/android-aarch64-toolchain.cmake'
rm 'cmake/android-armhf-toolchain.cmake'
rm 'cmake/fix-macos-libs.sh'
rm 'cmake/gpl.txt'
Updated 16 paths from 79117dc
Updating ci
rm 'ci/check-key-password'
rm 'ci/circleci-build-android.sh'
rm 'ci/circleci-build-debian.sh'
rm 'ci/circleci-build-flatpak.sh'
rm 'ci/circleci-build-macos.sh'
rm 'ci/drone-build-raspbian.sh'
rm 'ci/generic-build-raspbian-armhf.sh'
rm 'ci/git-push'
rm 'ci/git-push.sh'
rm 'ci/new-credentials'
rm 'ci/travis-build-win32.sh'
rm 'ci/upload.bat.in'
rm 'ci/upload.sh.in'
rm 'ci/windows-ldd'
Updated 14 paths from 79117dc
[v3.0 3ac86de] Templates: Updating ci
 3 files changed, 2 insertions(+), 2 deletions(-)
 mode change 100644 => 100755 ci/git-push.sh
Updating scripts
rm 'scripts/local-build'
rm 'scripts/local-build.rc'
rm 'scripts/local-upload'
rm 'scripts/pre-commit'
Updated 4 paths from 79117dc
[v3.0 9a52d93] Templates: Updating scripts
 4 files changed, 1 insertion(+), 9 deletions(-)
 mode change 100644 => 100755 scripts/local-build
 mode change 100644 => 100755 scripts/local-upload
 mode change 100644 => 100755 scripts/pre-commit
Updating buildwin
rm 'buildwin/LB-wo-clone.bat'
rm 'buildwin/ShipDriver.clone.bat'
rm 'buildwin/ShipDriver.clone.bat.bak'
rm 'buildwin/ShipDriver.without.clone.bat.bak'
rm 'buildwin/win_deps.bat'
rm 'buildwin/win_deps.bat.bak'
rm 'buildwin/wxWidgets-3.1.2.7z'
Updated 3 paths from 79117dc
[v3.0 0b2336f] Templates: Updating buildwin
 6 files changed, 4 insertions(+), 92 deletions(-)
 delete mode 100644 buildwin/ShipDriver.clone.bat.bak
 rename buildwin/{LB-wo-clone.bat => ShipDriver.without.clone.bat} (96%)
 delete mode 100644 buildwin/ShipDriver.without.clone.bat.bak
 delete mode 100644 buildwin/win_deps.bat.bak
 delete mode 100644 buildwin/wxWidgets-3.1.2.7z
Updating libs
Updated 6 paths from 79117dc
[v3.0 8803d4b] Templates: Updating libs
 6 files changed, 6 insertions(+), 2 deletions(-)
 mode change 100644 => 100755 libs/jsoncpp/.travis_scripts/cmake_builder.sh
 mode change 100644 => 100755 libs/jsoncpp/.travis_scripts/meson_builder.sh
 mode change 100644 => 100755 libs/jsoncpp/.travis_scripts/run-clang-format.py
 mode change 100644 => 100755 libs/jsoncpp/.travis_scripts/run-clang-format.sh
 mode change 100644 => 100755 libs/jsoncpp/amalgamate.py
Templates: Updating other files
Updated 0 paths from 79117dc
rm '.circleci/config.yml'
Updated 1 path from 79117dc
Updated 0 paths from 79117dc
Updated 0 paths from 79117dc
Updated 0 paths from 79117dc
Updated 0 paths from 79117dc
Updated 1 path from 79117dc
Updated 1 path from 79117dc
Updated 0 paths from 79117dc
Updated 0 paths from 79117dc
Updated 0 paths from 79117dc
Updated 0 paths from 79117dc
Updated 0 paths from 79117dc
[v3.0 b2e80c8] Templates: Updating other files
 2 files changed, 5 insertions(+), 6 deletions(-)
Create or update cmake/TemplateVersion
[v3.0 38f5faf] cmake: Update TemplateVersion to e49825d
 1 file changed, 4 insertions(+)
 create mode 100644 cmake/TemplateVersion


Shipdriver templates has been updated. To review changes made:

    $ git log --oneline -5

See UPDATE_TEMPLATES.md for more.
```

**Comment by rgleason** [comment] 2022-01-09 01:15
### Inspecting what happened.
1. local build using my own bld.bat continues to work as it did before.
2. Imported Plugin   *.gz and it seems to work ok.
2. libs - it appears that all libs in shipdriver_pi got copied to logbookkonni_pi
3. Logbook  libs/plugingl  was different, and now conforms to shipdriver's version. Unknown if this is a problem yet.
4. Will report further after these changes are committed and pushed with a tag

**Comment by rgleason** [comment] 2022-01-09 02:30
Appveyor worked,   https://github.com/rgleason/LogbookKonni_pi/tree/v3.0
Everything else failed. https://github.com/rgleason/LogbookKonni_pi/runs/4750886367

Found 4 raspbian packages in  "beta" https://cloudsmith.io/~opencpn/repos/logbookkonni-beta/packages/  
and 10 packages in  "alpha"  https://cloudsmith.io/~opencpn/repos/logbookkonni-alpha/packages/?q=1.4.26
Why?

Because I pushed the tag last, I decided that I should
git commit --allow-empty -m "Trigger build"
git push origin

and it started building again and is going into "alpha" with no "beta1" in the title.

I am not really understanding how I control where the builds land.
I thought having a commit with "1.2.3-beta1" would land builds in the "beta" branch.

**Comment by leamas** [comment] 2022-01-09 08:48
> Everything else failed

After working so long with these issues, why do you file such things?

Macos fails with message ` ERROR: Cannot decrypt private key (wrong GIT_KEY_PASSWORD?)`  Seems pretty clear. Have you looked at the logs?

Flatpak builds fails after not  building at all. Have you reviewed the flatpak manifest? Flatpak builds from the master branch, does this match the realities?

**Comment by leamas** [comment] 2022-01-09 08:50
> This is necessary to avoid the previous errors.

No, it's not. What's necessary is to not use the -T flag.

**Comment by rgleason** [comment] 2022-01-09 13:50
I never executed 

```
Does it need to be

./update-templates -T ./shipdriver/v3.0
```

This should be explained in the update-templates.md
```
./update-templates -l
Adds a new remote!! This is necessary to avoid the previous errors.
The manual should mention this as a first necessary step.
```

**Comment by leamas** [comment] 2022-01-09 13:53
> Does it need to be [...]

No,. Again: the problems you run into are caused by using the -T  option.  There is no documentation suggesting you should,  and I have also said you should not.  So: why are you (still!) using it?

**Comment by leamas** [comment] 2022-01-09 13:56
And: if you check the help message from updates-templates, it suggests that the normal use case is using a tag, not a branch. There is a sd3.0.2-beta1, I suggest that you use that. It's beta, but since sd3.0.1 is broken it is your best bet.

**Comment by rgleason** [comment] 2022-01-09 14:11
Yes I have looked at the logs.  Where do you find this?  I haven't found it.
`Macos fails with message ERROR: Cannot decrypt private key (wrong GIT_KEY_PASSWORD?) Seems pretty clear. Have you looked at the logs?  
`
I have checked and redone the git_rep and git_key_password  in Circleci.

OK, thanks.
`Flatpak builds fails after not building at all. Have you reviewed the flatpak manifest? Flatpak builds from the master branch, does this match the realities?`

**Comment by leamas** [comment] 2022-01-09 14:15
> Yes I have looked at the logs. Where do you find this? I haven't found it.

In the CirclerCI logs, available after clicking on the builds. ALl builds except flatpak seems to end the same way.

If I get this right, you had the right password in appveyor and the wrong in CircleCI. If you change the pw, don't forget to update inn all places.

As for flatpak, I'll make a try to apply update-templates later to sort things out. No idea what's going on in that case.

**Comment by leamas** [comment] 2022-01-09 16:02
I have made try with LogBook from current master branch at ` 6826d72 (rgleason/master) Trigger build`.

Doing so, I followed the cookbook in UPDATE_TEMPLATES.md verbatim. No shortcuts by copying any file or using any GUI, this is known to cause troubles. So, again: as of UPDATE_TEMPLATES.md, verbatim. The tag I used to update templates was _sd3.0.2-beta1_.

The results basically looked fine, but flatpak builds did not work. Fixed by removing the file _.gitmodules_ (a left-over after experimenting with opencpn-libs).

Pushed to github. Everything works except the Android builds. These errors are source code problems, out of scope for the templates. Logs available [here](https://app.circleci.com/pipelines/github/leamas/LogbookKonni_pi)

**Comment by leamas** [comment] 2022-01-09 16:11
Here is my git log which resulted   in the CircleCI build log above. 
```
9b013de (HEAD -> master, origin/master) Remove .gitmodules left-over.
7e29054 cmake: Update TemplateVersion to e49825d
a72273e Templates: Updating other files
cb0aba0 Templates: Updating libs
905fea2 Templates: Updating buildwin
9b5c52c Templates: Updating scripts
cfb53cb Templates: Updating ci
be70907 update-templates: Updated to 3.0.2-beta1
460c4b5 Add update-templates script
6826d72 (rgleason/master) Trigger build
```

**Comment by rgleason** [comment] 2022-01-09 18:11
I used that tag too, and I did not copy any files over, the output results are pasted in above..   

`./update templates  sd3.0.2-beta1`

See https://github.com/Rasbats/shipdriver_pi/issues/387#issuecomment-1008202355

but I made a new branch called 'v3.0'  and have pushed that.

I will remove .gitmodules.

**Comment by rgleason** [comment] 2022-01-10 00:29
I made the branch because it was the first time doing this and I did not trust update-templates script.   As it was it overwrote lib/plugingl which was different than shipdriver.  It seems to be working, but that "feature" overwriting lib directories, is on my watch out list.

**Closed** 2022-01-10 01:30 UTC
